AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - Amazon API Gateway REST API with S3 integration
Resources:
 
  ETLJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: s3://maddy-proarch/
      DefaultArguments:
        --TempDir: s3://my-temp-dir
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 3
      Name:  proarch-etljob13
      Role: arn:aws:iam::944196645553:role/GlueServiceRole
      Timeout: 2880
      GlueVersion: '2.0'

  ETLTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: SCHEDULED
      Schedule: rate(5 minutes)
      Actions:
        - JobName: !Ref ETLJob

  ETLS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: targetbucket1-etl

  ETLLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://maddy-proarch/my_lambda.zip
      Handler: index.handler
      Runtime: python3.8
      Timeout: 30
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref ETLS3Bucket
            Events: s3:ObjectCreated:*

  ETLDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:  proarch-dynamodbtable1
